repos:
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black
      name: Format fix
      language_version: python3
    - id: black-jupyter
      name: ipynb format fix
      language_version: python3
      additional_dependencies: [".[jupyter]"]

- repo: local
  hooks:

    - id: jupyisort
      name: Sorts ipynb imports
      entry: jupytext --pipe-fmt ".py" --pipe "isort - --multi-line=3 --trailing-comma --force-grid-wrap=0 --use-parentheses --line-width=99" --sync
      files: \.ipynb$
      language: python
